# Supplier: openai, azure
supplier: "openai"

# If supplier is OpenAI, please set this value
api-key: "<INSERT YOUR OPENAI API KEY HERE>"
model: "gpt-3.5-turbo"

# If supplier is Azure, please set this value
azure_endpoint: "https://xxxx.openai.azure.com/"
azure_api_version: "2023-07-01-preview"
azure_api_key: "<INSERT YOUR AZURE API KEY HERE>"
azure_deployment_name: "gpt-35-turbo"
azure_deployment_name_eb: "text-embedding-ada-002"

# Settings
temperature: 1
#max_tokens: 500 
markdown: true
easy_copy: true